<?php

/**
 * @file
 * Functions to support theming in the test_stable theme.
 */

/**
 * Implements hook_preprocess_HOOK() for html.html.twig.
 */
function test_stable_preprocess_html(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for page.html.twig.
 */
function test_stable_preprocess_page(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for node.html.twig.
 */
function test_stable_preprocess_node(&$variables) {

}
